[workspace]
members = ["crates/domain", "crates/application", "crates/storage-sqlite", "apps/desktop/src-tauri"]
default-members = ["crates/domain", "crates/application", "crates/storage-sqlite"]
resolver = "2"

[workspace.package]
version = "0.1.0-beta.1"
edition = "2021"
license = "AGPL-3.0-or-later"
authors = ["Aleksa Dimitrijević"]

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
uuid = { version = "1", features = ["v4", "serde"] }
