[package]
name = "librett-desktop"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
librett-domain = { path = "../../../crates/domain" }
librett-application = { path = "../../../crates/application" }
librett-storage-sqlite = { path = "../../../crates/storage-sqlite" }
uuid.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
glib = "0.18"

[target.'cfg(target_os = "macos")'.dependencies]
objc2-web-kit = { version = "0.3", default-features = false, features = ["std", "WKWebView"] }
