ALTER TABLE players ADD COLUMN birth_year INTEGER CHECK (birth_year BETWEEN 1900 AND 2100);
ALTER TABLE players ADD COLUMN city TEXT NOT NULL DEFAULT '';
ALTER TABLE players ADD COLUMN country TEXT NOT NULL DEFAULT '';
ALTER TABLE players ADD COLUMN email TEXT NOT NULL DEFAULT '';
ALTER TABLE players ADD COLUMN phone TEXT NOT NULL DEFAULT '';
ALTER TABLE players ADD COLUMN notes TEXT NOT NULL DEFAULT '';
ALTER TABLE players ADD COLUMN photo TEXT;
PRAGMA user_version = 3;
