-- Global action history. Snapshots intentionally omit image bytes.
CREATE TABLE action_history (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 occurred_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
 kind TEXT NOT NULL, action TEXT NOT NULL, entity_type TEXT NOT NULL,
 entity_id TEXT NOT NULL, entity_name TEXT NOT NULL,
 tournament_id TEXT, tournament_name TEXT, category_id TEXT, category_name TEXT,
 before_data TEXT CHECK(before_data IS NULL OR json_valid(before_data)),
 after_data TEXT CHECK(after_data IS NULL OR json_valid(after_data)),
 historical INTEGER NOT NULL DEFAULT 0 CHECK(historical IN (0,1))
);
CREATE INDEX history_time ON action_history(occurred_at DESC,id DESC);
CREATE INDEX history_kind ON action_history(kind,occurred_at DESC,id DESC);
CREATE INDEX history_tournament ON action_history(tournament_id,occurred_at DESC,id DESC);
CREATE INDEX history_category ON action_history(category_id,occurred_at DESC,id DESC);
CREATE TRIGGER history_no_update BEFORE UPDATE ON action_history BEGIN SELECT RAISE(ABORT,'Action history is immutable'); END;
CREATE TRIGGER history_no_delete BEFORE DELETE ON action_history BEGIN SELECT RAISE(ABORT,'Action history is immutable'); END;

INSERT INTO action_history(occurred_at,kind,action,entity_type,entity_id,entity_name,tournament_id,tournament_name,category_id,category_name,after_data,historical) SELECT h.created_at,'draws','recorded','category_draws',h.id,'Žreb / Draw', (SELECT tournament_id FROM categories WHERE id=h.category_id),(SELECT name FROM tournaments WHERE id=(SELECT tournament_id FROM categories WHERE id=h.category_id)),h.category_id,(SELECT name FROM categories WHERE id=h.category_id),json_object('revision',revision,'payload',payload),1 FROM category_draws h ORDER BY h.created_at;

INSERT INTO action_history(occurred_at,kind,action,entity_type,entity_id,entity_name,tournament_id,tournament_name,category_id,category_name,after_data,historical) SELECT h.recorded_at,'results','recorded','match_results',h.id,match_key, (SELECT tournament_id FROM categories WHERE id=(SELECT category_id FROM category_draws WHERE id=h.draw_id)),(SELECT name FROM tournaments WHERE id=(SELECT tournament_id FROM categories WHERE id=(SELECT category_id FROM category_draws WHERE id=h.draw_id))),(SELECT category_id FROM category_draws WHERE id=h.draw_id),(SELECT name FROM categories WHERE id=(SELECT category_id FROM category_draws WHERE id=h.draw_id)),json_object('match_key',h.match_key,'revision',h.revision,'payload',h.payload,'first_name',(SELECT group_concat(name_snapshot,' / ') FROM entry_members WHERE entry_id=json_extract(h.payload,'$.first')),'first_members',json((SELECT json_group_array(json_object('name',name_snapshot,'club',club_snapshot)) FROM entry_members WHERE entry_id=json_extract(h.payload,'$.first'))),'second_name',(SELECT group_concat(name_snapshot,' / ') FROM entry_members WHERE entry_id=json_extract(h.payload,'$.second')),'second_members',json((SELECT json_group_array(json_object('name',name_snapshot,'club',club_snapshot)) FROM entry_members WHERE entry_id=json_extract(h.payload,'$.second'))),'winner_name',(SELECT group_concat(name_snapshot,' / ') FROM entry_members WHERE entry_id=json_extract(h.payload,'$.winner')),'winner_members',json((SELECT json_group_array(json_object('name',name_snapshot,'club',club_snapshot)) FROM entry_members WHERE entry_id=json_extract(h.payload,'$.winner')))),1 FROM match_results h ORDER BY h.recorded_at;

INSERT INTO action_history(occurred_at,kind,action,entity_type,entity_id,entity_name,tournament_id,tournament_name,category_id,category_name,after_data,historical) SELECT h.created_at,'cash',h.kind,'cash_records',h.id,kind, (SELECT tournament_id FROM categories WHERE id=(SELECT category_id FROM entries WHERE id=h.entry_id)),(SELECT name FROM tournaments WHERE id=(SELECT tournament_id FROM categories WHERE id=(SELECT category_id FROM entries WHERE id=h.entry_id))),(SELECT category_id FROM entries WHERE id=h.entry_id),(SELECT name FROM categories WHERE id=(SELECT category_id FROM entries WHERE id=h.entry_id)),json_object('kind',kind,'amount_minor',amount_minor,'note',note),1 FROM cash_records h ORDER BY h.created_at;

INSERT INTO action_history(occurred_at,kind,action,entity_type,entity_id,entity_name,tournament_id,tournament_name,category_id,category_name,after_data,historical) SELECT h.recorded_at,'completion',CASE WHEN json_extract(h.payload,'$.completion.completed_at') IS NULL THEN 'reopened' ELSE 'completed' END,'completion_history',h.entity_id,'Završetak / Completion', CASE WHEN h.entity_kind='tournament' THEN h.entity_id ELSE (SELECT tournament_id FROM categories WHERE id=h.entity_id) END,(SELECT name FROM tournaments WHERE id=CASE WHEN h.entity_kind='tournament' THEN h.entity_id ELSE (SELECT tournament_id FROM categories WHERE id=h.entity_id) END),CASE WHEN h.entity_kind='category' THEN h.entity_id ELSE NULL END,(SELECT name FROM categories WHERE id=CASE WHEN h.entity_kind='category' THEN h.entity_id ELSE NULL END),json_object('revision',revision,'payload',payload),1 FROM completion_history h ORDER BY h.recorded_at;

INSERT INTO action_history(occurred_at,kind,action,entity_type,entity_id,entity_name,tournament_id,tournament_name,category_id,category_name,after_data,historical) SELECT h.deleted_at,'trash','recorded','tournament_trash',h.tournament_id,'Korpa / Trash', h.tournament_id,(SELECT name FROM tournaments WHERE id=h.tournament_id),NULL,(SELECT name FROM categories WHERE id=NULL),NULL,1 FROM tournament_trash h ORDER BY h.deleted_at;

CREATE TRIGGER history_tournaments_insert AFTER INSERT ON tournaments
BEGIN INSERT INTO action_history(kind,action,entity_type,entity_id,entity_name,tournament_id,tournament_name,category_id,category_name,before_data,after_data) VALUES('tournaments','created','tournaments',NEW.id,NEW.name,NEW.id,NEW.name,NULL,(SELECT name FROM categories WHERE id=NULL),NULL,json_object('name',NEW.name)); END;

CREATE TRIGGER history_tournaments_update AFTER UPDATE ON tournaments WHEN OLD.name IS NOT NEW.name
BEGIN INSERT INTO action_history(kind,action,entity_type,entity_id,entity_name,tournament_id,tournament_name,category_id,category_name,before_data,after_data) VALUES('tournaments','updated','tournaments',NEW.id,NEW.name,NEW.id,NEW.name,NULL,(SELECT name FROM categories WHERE id=NULL),json_object('name',OLD.name),json_object('name',NEW.name)); END;

CREATE TRIGGER history_tournaments_delete AFTER DELETE ON tournaments
BEGIN INSERT INTO action_history(kind,action,entity_type,entity_id,entity_name,tournament_id,tournament_name,category_id,category_name,before_data,after_data) VALUES('tournaments','deleted','tournaments',OLD.id,OLD.name,OLD.id,OLD.name,NULL,(SELECT name FROM categories WHERE id=NULL),json_object('name',OLD.name),NULL); END;

CREATE TRIGGER history_tournament_cover AFTER UPDATE OF cover ON tournaments WHEN OLD.cover IS NOT NEW.cover BEGIN INSERT INTO action_history(kind,action,entity_type,entity_id,entity_name,tournament_id,tournament_name,before_data,after_data) VALUES('tournaments','image_changed','tournaments',NEW.id,NEW.name,NEW.id,NEW.name,json_object('has_image',OLD.cover IS NOT NULL),json_object('has_image',NEW.cover IS NOT NULL)); END;

CREATE TRIGGER history_categories_insert AFTER INSERT ON categories
BEGIN INSERT INTO action_history(kind,action,entity_type,entity_id,entity_name,tournament_id,tournament_name,category_id,category_name,before_data,after_data) VALUES('categories','created','categories',NEW.id,NEW.name,NEW.tournament_id,(SELECT name FROM tournaments WHERE id=NEW.tournament_id),NEW.id,NEW.name,NULL,json_object('name',NEW.name,'discipline',NEW.discipline,'format',NEW.format,'fee_minor',NEW.fee_minor,'archived',NEW.archived)); END;

CREATE TRIGGER history_categories_update AFTER UPDATE ON categories WHEN OLD.name IS NOT NEW.name OR OLD.discipline IS NOT NEW.discipline OR OLD.format IS NOT NEW.format OR OLD.fee_minor IS NOT NEW.fee_minor OR OLD.archived IS NOT NEW.archived
BEGIN INSERT INTO action_history(kind,action,entity_type,entity_id,entity_name,tournament_id,tournament_name,category_id,category_name,before_data,after_data) VALUES('categories',CASE WHEN OLD.archived IS NOT NEW.archived THEN CASE WHEN NEW.archived=1 THEN 'archived' ELSE 'restored' END ELSE 'updated' END,'categories',NEW.id,NEW.name,NEW.tournament_id,(SELECT name FROM tournaments WHERE id=NEW.tournament_id),NEW.id,NEW.name,json_object('name',OLD.name,'discipline',OLD.discipline,'format',OLD.format,'fee_minor',OLD.fee_minor,'archived',OLD.archived),json_object('name',NEW.name,'discipline',NEW.discipline,'format',NEW.format,'fee_minor',NEW.fee_minor,'archived',NEW.archived)); END;

CREATE TRIGGER history_categories_delete AFTER DELETE ON categories
BEGIN INSERT INTO action_history(kind,action,entity_type,entity_id,entity_name,tournament_id,tournament_name,category_id,category_name,before_data,after_data) VALUES('categories','deleted','categories',OLD.id,OLD.name,OLD.tournament_id,(SELECT name FROM tournaments WHERE id=OLD.tournament_id),OLD.id,OLD.name,json_object('name',OLD.name,'discipline',OLD.discipline,'format',OLD.format,'fee_minor',OLD.fee_minor,'archived',OLD.archived),NULL); END;

CREATE TRIGGER history_players_insert AFTER INSERT ON players
BEGIN INSERT INTO action_history(kind,action,entity_type,entity_id,entity_name,tournament_id,tournament_name,category_id,category_name,before_data,after_data) VALUES('players','created','players',NEW.id,NEW.name,NULL,(SELECT name FROM tournaments WHERE id=NULL),NULL,(SELECT name FROM categories WHERE id=NULL),NULL,json_object('name',NEW.name,'club',NEW.club,'birth_year',NEW.birth_year,'city',NEW.city,'country',NEW.country,'email',NEW.email,'phone',NEW.phone,'notes',NEW.notes)); END;

CREATE TRIGGER history_players_update AFTER UPDATE ON players WHEN OLD.name IS NOT NEW.name OR OLD.club IS NOT NEW.club OR OLD.birth_year IS NOT NEW.birth_year OR OLD.city IS NOT NEW.city OR OLD.country IS NOT NEW.country OR OLD.email IS NOT NEW.email OR OLD.phone IS NOT NEW.phone OR OLD.notes IS NOT NEW.notes
BEGIN INSERT INTO action_history(kind,action,entity_type,entity_id,entity_name,tournament_id,tournament_name,category_id,category_name,before_data,after_data) VALUES('players','updated','players',NEW.id,NEW.name,NULL,(SELECT name FROM tournaments WHERE id=NULL),NULL,(SELECT name FROM categories WHERE id=NULL),json_object('name',OLD.name,'club',OLD.club,'birth_year',OLD.birth_year,'city',OLD.city,'country',OLD.country,'email',OLD.email,'phone',OLD.phone,'notes',OLD.notes),json_object('name',NEW.name,'club',NEW.club,'birth_year',NEW.birth_year,'city',NEW.city,'country',NEW.country,'email',NEW.email,'phone',NEW.phone,'notes',NEW.notes)); END;

CREATE TRIGGER history_players_delete AFTER DELETE ON players
BEGIN INSERT INTO action_history(kind,action,entity_type,entity_id,entity_name,tournament_id,tournament_name,category_id,category_name,before_data,after_data) VALUES('players','deleted','players',OLD.id,OLD.name,NULL,(SELECT name FROM tournaments WHERE id=NULL),NULL,(SELECT name FROM categories WHERE id=NULL),json_object('name',OLD.name,'club',OLD.club,'birth_year',OLD.birth_year,'city',OLD.city,'country',OLD.country,'email',OLD.email,'phone',OLD.phone,'notes',OLD.notes),NULL); END;

CREATE TRIGGER history_player_photo AFTER UPDATE OF photo ON players WHEN OLD.photo IS NOT NEW.photo BEGIN INSERT INTO action_history(kind,action,entity_type,entity_id,entity_name,before_data,after_data) VALUES('players','image_changed','players',NEW.id,NEW.name,json_object('has_image',OLD.photo IS NOT NULL),json_object('has_image',NEW.photo IS NOT NULL)); END;

CREATE TRIGGER history_entries_insert AFTER INSERT ON entries
BEGIN INSERT INTO action_history(kind,action,entity_type,entity_id,entity_name,tournament_id,tournament_name,category_id,category_name,before_data,after_data) VALUES('registrations','created','entries',NEW.id,COALESCE((SELECT group_concat(name_snapshot,' / ') FROM entry_members WHERE entry_id=NEW.id),'Prijava / Registration'),(SELECT tournament_id FROM categories WHERE id=NEW.category_id),(SELECT name FROM tournaments WHERE id=(SELECT tournament_id FROM categories WHERE id=NEW.category_id)),NEW.category_id,(SELECT name FROM categories WHERE id=NEW.category_id),NULL,json_object('status',NEW.status)); END;

CREATE TRIGGER history_entries_update AFTER UPDATE ON entries WHEN OLD.status IS NOT NEW.status
BEGIN INSERT INTO action_history(kind,action,entity_type,entity_id,entity_name,tournament_id,tournament_name,category_id,category_name,before_data,after_data) VALUES('registrations','updated','entries',NEW.id,COALESCE((SELECT group_concat(name_snapshot,' / ') FROM entry_members WHERE entry_id=NEW.id),'Prijava / Registration'),(SELECT tournament_id FROM categories WHERE id=NEW.category_id),(SELECT name FROM tournaments WHERE id=(SELECT tournament_id FROM categories WHERE id=NEW.category_id)),NEW.category_id,(SELECT name FROM categories WHERE id=NEW.category_id),json_object('status',OLD.status),json_object('status',NEW.status)); END;

CREATE TRIGGER history_entries_delete AFTER DELETE ON entries
BEGIN INSERT INTO action_history(kind,action,entity_type,entity_id,entity_name,tournament_id,tournament_name,category_id,category_name,before_data,after_data) VALUES('registrations','deleted','entries',OLD.id,COALESCE((SELECT group_concat(name_snapshot,' / ') FROM entry_members WHERE entry_id=OLD.id),'Prijava / Registration'),(SELECT tournament_id FROM categories WHERE id=OLD.category_id),(SELECT name FROM tournaments WHERE id=(SELECT tournament_id FROM categories WHERE id=OLD.category_id)),OLD.category_id,(SELECT name FROM categories WHERE id=OLD.category_id),json_object('status',OLD.status),NULL); END;

CREATE TRIGGER history_entry_members_insert AFTER INSERT ON entry_members
BEGIN INSERT INTO action_history(kind,action,entity_type,entity_id,entity_name,tournament_id,tournament_name,category_id,category_name,before_data,after_data) VALUES('registrations','created','entry_members',NEW.entry_id,NEW.name_snapshot,(SELECT tournament_id FROM categories WHERE id=NEW.category_id),(SELECT name FROM tournaments WHERE id=(SELECT tournament_id FROM categories WHERE id=NEW.category_id)),NEW.category_id,(SELECT name FROM categories WHERE id=NEW.category_id),NULL,json_object('name_snapshot',NEW.name_snapshot,'club_snapshot',NEW.club_snapshot,'position',NEW.position)); END;

CREATE TRIGGER history_entry_members_delete AFTER DELETE ON entry_members
BEGIN INSERT INTO action_history(kind,action,entity_type,entity_id,entity_name,tournament_id,tournament_name,category_id,category_name,before_data,after_data) VALUES('registrations','deleted','entry_members',OLD.entry_id,OLD.name_snapshot,(SELECT tournament_id FROM categories WHERE id=OLD.category_id),(SELECT name FROM tournaments WHERE id=(SELECT tournament_id FROM categories WHERE id=OLD.category_id)),OLD.category_id,(SELECT name FROM categories WHERE id=OLD.category_id),json_object('name_snapshot',OLD.name_snapshot,'club_snapshot',OLD.club_snapshot,'position',OLD.position),NULL); END;

CREATE TRIGGER history_player_attendance_insert AFTER INSERT ON player_attendance
BEGIN INSERT INTO action_history(kind,action,entity_type,entity_id,entity_name,tournament_id,tournament_name,category_id,category_name,before_data,after_data) VALUES('attendance','created','player_attendance',NEW.player_id,(SELECT name FROM players WHERE id=NEW.player_id),NEW.tournament_id,(SELECT name FROM tournaments WHERE id=NEW.tournament_id),NULL,(SELECT name FROM categories WHERE id=NULL),NULL,json_object('checked_in',NEW.checked_in)); END;

CREATE TRIGGER history_player_attendance_update AFTER UPDATE ON player_attendance WHEN OLD.checked_in IS NOT NEW.checked_in
BEGIN INSERT INTO action_history(kind,action,entity_type,entity_id,entity_name,tournament_id,tournament_name,category_id,category_name,before_data,after_data) VALUES('attendance','updated','player_attendance',NEW.player_id,(SELECT name FROM players WHERE id=NEW.player_id),NEW.tournament_id,(SELECT name FROM tournaments WHERE id=NEW.tournament_id),NULL,(SELECT name FROM categories WHERE id=NULL),json_object('checked_in',OLD.checked_in),json_object('checked_in',NEW.checked_in)); END;

CREATE TRIGGER history_player_attendance_delete AFTER DELETE ON player_attendance
BEGIN INSERT INTO action_history(kind,action,entity_type,entity_id,entity_name,tournament_id,tournament_name,category_id,category_name,before_data,after_data) VALUES('attendance','deleted','player_attendance',OLD.player_id,(SELECT name FROM players WHERE id=OLD.player_id),OLD.tournament_id,(SELECT name FROM tournaments WHERE id=OLD.tournament_id),NULL,(SELECT name FROM categories WHERE id=NULL),json_object('checked_in',OLD.checked_in),NULL); END;

CREATE TRIGGER history_category_configurations_insert AFTER INSERT ON category_configurations
BEGIN INSERT INTO action_history(kind,action,entity_type,entity_id,entity_name,tournament_id,tournament_name,category_id,category_name,before_data,after_data) VALUES('rules','created','category_configurations',NEW.category_id,'Pravila / Rules',(SELECT tournament_id FROM categories WHERE id=NEW.category_id),(SELECT name FROM tournaments WHERE id=(SELECT tournament_id FROM categories WHERE id=NEW.category_id)),NEW.category_id,(SELECT name FROM categories WHERE id=NEW.category_id),NULL,json_object('revision',NEW.revision,'payload',NEW.payload)); END;

CREATE TRIGGER history_category_configurations_update AFTER UPDATE ON category_configurations WHEN OLD.revision IS NOT NEW.revision OR OLD.payload IS NOT NEW.payload
BEGIN INSERT INTO action_history(kind,action,entity_type,entity_id,entity_name,tournament_id,tournament_name,category_id,category_name,before_data,after_data) VALUES('rules','updated','category_configurations',NEW.category_id,'Pravila / Rules',(SELECT tournament_id FROM categories WHERE id=NEW.category_id),(SELECT name FROM tournaments WHERE id=(SELECT tournament_id FROM categories WHERE id=NEW.category_id)),NEW.category_id,(SELECT name FROM categories WHERE id=NEW.category_id),json_object('revision',OLD.revision,'payload',OLD.payload),json_object('revision',NEW.revision,'payload',NEW.payload)); END;

CREATE TRIGGER history_category_configurations_delete AFTER DELETE ON category_configurations
BEGIN INSERT INTO action_history(kind,action,entity_type,entity_id,entity_name,tournament_id,tournament_name,category_id,category_name,before_data,after_data) VALUES('rules','deleted','category_configurations',OLD.category_id,'Pravila / Rules',(SELECT tournament_id FROM categories WHERE id=OLD.category_id),(SELECT name FROM tournaments WHERE id=(SELECT tournament_id FROM categories WHERE id=OLD.category_id)),OLD.category_id,(SELECT name FROM categories WHERE id=OLD.category_id),json_object('revision',OLD.revision,'payload',OLD.payload),NULL); END;

CREATE TRIGGER history_category_draws_insert AFTER INSERT ON category_draws
BEGIN INSERT INTO action_history(kind,action,entity_type,entity_id,entity_name,tournament_id,tournament_name,category_id,category_name,before_data,after_data) VALUES('draws','created','category_draws',NEW.id,'Žreb / Draw',(SELECT tournament_id FROM categories WHERE id=NEW.category_id),(SELECT name FROM tournaments WHERE id=(SELECT tournament_id FROM categories WHERE id=NEW.category_id)),NEW.category_id,(SELECT name FROM categories WHERE id=NEW.category_id),(SELECT json_object('revision',d.revision,'payload',d.payload) FROM category_draws d WHERE d.category_id=NEW.category_id AND d.revision<NEW.revision ORDER BY d.revision DESC LIMIT 1),json_object('revision',NEW.revision,'payload',NEW.payload)); END;

CREATE TRIGGER history_match_results_insert AFTER INSERT ON match_results
BEGIN INSERT INTO action_history(kind,action,entity_type,entity_id,entity_name,tournament_id,tournament_name,category_id,category_name,before_data,after_data) VALUES('results',CASE WHEN NEW.payload='null' THEN 'invalidated' WHEN NEW.revision>1 THEN 'corrected' ELSE 'recorded' END,'match_results',NEW.id,NEW.match_key,(SELECT tournament_id FROM categories WHERE id=(SELECT category_id FROM category_draws WHERE id=NEW.draw_id)),(SELECT name FROM tournaments WHERE id=(SELECT tournament_id FROM categories WHERE id=(SELECT category_id FROM category_draws WHERE id=NEW.draw_id))),(SELECT category_id FROM category_draws WHERE id=NEW.draw_id),(SELECT name FROM categories WHERE id=(SELECT category_id FROM category_draws WHERE id=NEW.draw_id)),(SELECT json_object('match_key',m.match_key,'revision',m.revision,'payload',m.payload,'first_name',(SELECT group_concat(name_snapshot,' / ') FROM entry_members WHERE entry_id=json_extract(m.payload,'$.first')),'first_members',json((SELECT json_group_array(json_object('name',name_snapshot,'club',club_snapshot)) FROM entry_members WHERE entry_id=json_extract(m.payload,'$.first'))),'second_name',(SELECT group_concat(name_snapshot,' / ') FROM entry_members WHERE entry_id=json_extract(m.payload,'$.second')),'second_members',json((SELECT json_group_array(json_object('name',name_snapshot,'club',club_snapshot)) FROM entry_members WHERE entry_id=json_extract(m.payload,'$.second'))),'winner_name',(SELECT group_concat(name_snapshot,' / ') FROM entry_members WHERE entry_id=json_extract(m.payload,'$.winner')),'winner_members',json((SELECT json_group_array(json_object('name',name_snapshot,'club',club_snapshot)) FROM entry_members WHERE entry_id=json_extract(m.payload,'$.winner')))) FROM match_results m WHERE m.draw_id=NEW.draw_id AND m.match_key=NEW.match_key AND m.revision<NEW.revision ORDER BY m.revision DESC LIMIT 1),json_object('match_key',NEW.match_key,'revision',NEW.revision,'payload',NEW.payload,'first_name',(SELECT group_concat(name_snapshot,' / ') FROM entry_members WHERE entry_id=json_extract(NEW.payload,'$.first')),'first_members',json((SELECT json_group_array(json_object('name',name_snapshot,'club',club_snapshot)) FROM entry_members WHERE entry_id=json_extract(NEW.payload,'$.first'))),'second_name',(SELECT group_concat(name_snapshot,' / ') FROM entry_members WHERE entry_id=json_extract(NEW.payload,'$.second')),'second_members',json((SELECT json_group_array(json_object('name',name_snapshot,'club',club_snapshot)) FROM entry_members WHERE entry_id=json_extract(NEW.payload,'$.second'))),'winner_name',(SELECT group_concat(name_snapshot,' / ') FROM entry_members WHERE entry_id=json_extract(NEW.payload,'$.winner')),'winner_members',json((SELECT json_group_array(json_object('name',name_snapshot,'club',club_snapshot)) FROM entry_members WHERE entry_id=json_extract(NEW.payload,'$.winner'))))); END;

CREATE TRIGGER history_group_orders_insert AFTER INSERT ON group_orders
BEGIN INSERT INTO action_history(kind,action,entity_type,entity_id,entity_name,tournament_id,tournament_name,category_id,category_name,before_data,after_data) VALUES('draws','created','group_orders',NEW.draw_id,'Plasman grupe / Group ranking',(SELECT tournament_id FROM categories WHERE id=(SELECT category_id FROM category_draws WHERE id=NEW.draw_id)),(SELECT name FROM tournaments WHERE id=(SELECT tournament_id FROM categories WHERE id=(SELECT category_id FROM category_draws WHERE id=NEW.draw_id))),(SELECT category_id FROM category_draws WHERE id=NEW.draw_id),(SELECT name FROM categories WHERE id=(SELECT category_id FROM category_draws WHERE id=NEW.draw_id)),NULL,json_object('group_number',NEW.group_number,'revision',NEW.revision,'payload',NEW.payload)); END;

CREATE TRIGGER history_group_orders_update AFTER UPDATE ON group_orders WHEN OLD.group_number IS NOT NEW.group_number OR OLD.revision IS NOT NEW.revision OR OLD.payload IS NOT NEW.payload
BEGIN INSERT INTO action_history(kind,action,entity_type,entity_id,entity_name,tournament_id,tournament_name,category_id,category_name,before_data,after_data) VALUES('draws','updated','group_orders',NEW.draw_id,'Plasman grupe / Group ranking',(SELECT tournament_id FROM categories WHERE id=(SELECT category_id FROM category_draws WHERE id=NEW.draw_id)),(SELECT name FROM tournaments WHERE id=(SELECT tournament_id FROM categories WHERE id=(SELECT category_id FROM category_draws WHERE id=NEW.draw_id))),(SELECT category_id FROM category_draws WHERE id=NEW.draw_id),(SELECT name FROM categories WHERE id=(SELECT category_id FROM category_draws WHERE id=NEW.draw_id)),json_object('group_number',OLD.group_number,'revision',OLD.revision,'payload',OLD.payload),json_object('group_number',NEW.group_number,'revision',NEW.revision,'payload',NEW.payload)); END;

CREATE TRIGGER history_group_orders_delete AFTER DELETE ON group_orders
BEGIN INSERT INTO action_history(kind,action,entity_type,entity_id,entity_name,tournament_id,tournament_name,category_id,category_name,before_data,after_data) VALUES('draws','deleted','group_orders',OLD.draw_id,'Plasman grupe / Group ranking',(SELECT tournament_id FROM categories WHERE id=(SELECT category_id FROM category_draws WHERE id=OLD.draw_id)),(SELECT name FROM tournaments WHERE id=(SELECT tournament_id FROM categories WHERE id=(SELECT category_id FROM category_draws WHERE id=OLD.draw_id))),(SELECT category_id FROM category_draws WHERE id=OLD.draw_id),(SELECT name FROM categories WHERE id=(SELECT category_id FROM category_draws WHERE id=OLD.draw_id)),json_object('group_number',OLD.group_number,'revision',OLD.revision,'payload',OLD.payload),NULL); END;

CREATE TRIGGER history_knockout_fillers_insert AFTER INSERT ON knockout_fillers
BEGIN INSERT INTO action_history(kind,action,entity_type,entity_id,entity_name,tournament_id,tournament_name,category_id,category_name,before_data,after_data) VALUES('draws','created','knockout_fillers',NEW.draw_id,'Nokaut mesta / Knockout slots',(SELECT tournament_id FROM categories WHERE id=(SELECT category_id FROM category_draws WHERE id=NEW.draw_id)),(SELECT name FROM tournaments WHERE id=(SELECT tournament_id FROM categories WHERE id=(SELECT category_id FROM category_draws WHERE id=NEW.draw_id))),(SELECT category_id FROM category_draws WHERE id=NEW.draw_id),(SELECT name FROM categories WHERE id=(SELECT category_id FROM category_draws WHERE id=NEW.draw_id)),NULL,json_object('revision',NEW.revision,'payload',NEW.payload)); END;

CREATE TRIGGER history_knockout_fillers_update AFTER UPDATE ON knockout_fillers WHEN OLD.revision IS NOT NEW.revision OR OLD.payload IS NOT NEW.payload
BEGIN INSERT INTO action_history(kind,action,entity_type,entity_id,entity_name,tournament_id,tournament_name,category_id,category_name,before_data,after_data) VALUES('draws','updated','knockout_fillers',NEW.draw_id,'Nokaut mesta / Knockout slots',(SELECT tournament_id FROM categories WHERE id=(SELECT category_id FROM category_draws WHERE id=NEW.draw_id)),(SELECT name FROM tournaments WHERE id=(SELECT tournament_id FROM categories WHERE id=(SELECT category_id FROM category_draws WHERE id=NEW.draw_id))),(SELECT category_id FROM category_draws WHERE id=NEW.draw_id),(SELECT name FROM categories WHERE id=(SELECT category_id FROM category_draws WHERE id=NEW.draw_id)),json_object('revision',OLD.revision,'payload',OLD.payload),json_object('revision',NEW.revision,'payload',NEW.payload)); END;

CREATE TRIGGER history_knockout_fillers_delete AFTER DELETE ON knockout_fillers
BEGIN INSERT INTO action_history(kind,action,entity_type,entity_id,entity_name,tournament_id,tournament_name,category_id,category_name,before_data,after_data) VALUES('draws','deleted','knockout_fillers',OLD.draw_id,'Nokaut mesta / Knockout slots',(SELECT tournament_id FROM categories WHERE id=(SELECT category_id FROM category_draws WHERE id=OLD.draw_id)),(SELECT name FROM tournaments WHERE id=(SELECT tournament_id FROM categories WHERE id=(SELECT category_id FROM category_draws WHERE id=OLD.draw_id))),(SELECT category_id FROM category_draws WHERE id=OLD.draw_id),(SELECT name FROM categories WHERE id=(SELECT category_id FROM category_draws WHERE id=OLD.draw_id)),json_object('revision',OLD.revision,'payload',OLD.payload),NULL); END;

CREATE TRIGGER history_cash_records_insert AFTER INSERT ON cash_records
BEGIN INSERT INTO action_history(kind,action,entity_type,entity_id,entity_name,tournament_id,tournament_name,category_id,category_name,before_data,after_data) VALUES('cash',NEW.kind,'cash_records',NEW.id,COALESCE((SELECT group_concat(name_snapshot,' / ') FROM entry_members WHERE entry_id=NEW.entry_id),'Blagajna / Cash'),(SELECT tournament_id FROM categories WHERE id=(SELECT category_id FROM entries WHERE id=NEW.entry_id)),(SELECT name FROM tournaments WHERE id=(SELECT tournament_id FROM categories WHERE id=(SELECT category_id FROM entries WHERE id=NEW.entry_id))),(SELECT category_id FROM entries WHERE id=NEW.entry_id),(SELECT name FROM categories WHERE id=(SELECT category_id FROM entries WHERE id=NEW.entry_id)),NULL,json_object('kind',NEW.kind,'amount_minor',NEW.amount_minor,'note',NEW.note)); END;

CREATE TRIGGER history_cash_allocations_insert AFTER INSERT ON cash_allocations
BEGIN INSERT INTO action_history(kind,action,entity_type,entity_id,entity_name,tournament_id,tournament_name,category_id,category_name,before_data,after_data) VALUES('cash','allocated','cash_allocations',NEW.record_id,(SELECT name FROM players WHERE id=NEW.player_id),(SELECT tournament_id FROM categories WHERE id=(SELECT category_id FROM entries WHERE id=(SELECT entry_id FROM cash_records WHERE id=NEW.record_id))),(SELECT name FROM tournaments WHERE id=(SELECT tournament_id FROM categories WHERE id=(SELECT category_id FROM entries WHERE id=(SELECT entry_id FROM cash_records WHERE id=NEW.record_id)))),(SELECT category_id FROM entries WHERE id=(SELECT entry_id FROM cash_records WHERE id=NEW.record_id)),(SELECT name FROM categories WHERE id=(SELECT category_id FROM entries WHERE id=(SELECT entry_id FROM cash_records WHERE id=NEW.record_id))),NULL,json_object('player_id',NEW.player_id,'amount_minor',NEW.amount_minor)); END;

CREATE TRIGGER history_match_assignments_insert AFTER INSERT ON match_assignments
BEGIN INSERT INTO action_history(kind,action,entity_type,entity_id,entity_name,tournament_id,tournament_name,category_id,category_name,before_data,after_data) VALUES('tables','created','match_assignments',NEW.draw_id,NEW.match_key,NEW.tournament_id,(SELECT name FROM tournaments WHERE id=NEW.tournament_id),(SELECT category_id FROM category_draws WHERE id=NEW.draw_id),(SELECT name FROM categories WHERE id=(SELECT category_id FROM category_draws WHERE id=NEW.draw_id)),NULL,json_object('match_key',NEW.match_key,'table_number',NEW.table_number,'status',NEW.status,'started_at',NEW.started_at)); END;

CREATE TRIGGER history_match_assignments_update AFTER UPDATE ON match_assignments WHEN OLD.match_key IS NOT NEW.match_key OR OLD.table_number IS NOT NEW.table_number OR OLD.status IS NOT NEW.status OR OLD.started_at IS NOT NEW.started_at
BEGIN INSERT INTO action_history(kind,action,entity_type,entity_id,entity_name,tournament_id,tournament_name,category_id,category_name,before_data,after_data) VALUES('tables','updated','match_assignments',NEW.draw_id,NEW.match_key,NEW.tournament_id,(SELECT name FROM tournaments WHERE id=NEW.tournament_id),(SELECT category_id FROM category_draws WHERE id=NEW.draw_id),(SELECT name FROM categories WHERE id=(SELECT category_id FROM category_draws WHERE id=NEW.draw_id)),json_object('match_key',OLD.match_key,'table_number',OLD.table_number,'status',OLD.status,'started_at',OLD.started_at),json_object('match_key',NEW.match_key,'table_number',NEW.table_number,'status',NEW.status,'started_at',NEW.started_at)); END;

CREATE TRIGGER history_match_assignments_delete AFTER DELETE ON match_assignments
BEGIN INSERT INTO action_history(kind,action,entity_type,entity_id,entity_name,tournament_id,tournament_name,category_id,category_name,before_data,after_data) VALUES('tables','deleted','match_assignments',OLD.draw_id,OLD.match_key,OLD.tournament_id,(SELECT name FROM tournaments WHERE id=OLD.tournament_id),(SELECT category_id FROM category_draws WHERE id=OLD.draw_id),(SELECT name FROM categories WHERE id=(SELECT category_id FROM category_draws WHERE id=OLD.draw_id)),json_object('match_key',OLD.match_key,'table_number',OLD.table_number,'status',OLD.status,'started_at',OLD.started_at),NULL); END;

CREATE TRIGGER history_tournament_scheduling_insert AFTER INSERT ON tournament_scheduling
BEGIN INSERT INTO action_history(kind,action,entity_type,entity_id,entity_name,tournament_id,tournament_name,category_id,category_name,before_data,after_data) VALUES('tables','created','tournament_scheduling',NEW.tournament_id,'Stolovi / Tables',NEW.tournament_id,(SELECT name FROM tournaments WHERE id=NEW.tournament_id),NULL,(SELECT name FROM categories WHERE id=NULL),NULL,json_object('table_count',NEW.table_count)); END;

CREATE TRIGGER history_tournament_scheduling_update AFTER UPDATE ON tournament_scheduling WHEN OLD.table_count IS NOT NEW.table_count
BEGIN INSERT INTO action_history(kind,action,entity_type,entity_id,entity_name,tournament_id,tournament_name,category_id,category_name,before_data,after_data) VALUES('tables','updated','tournament_scheduling',NEW.tournament_id,'Stolovi / Tables',NEW.tournament_id,(SELECT name FROM tournaments WHERE id=NEW.tournament_id),NULL,(SELECT name FROM categories WHERE id=NULL),json_object('table_count',OLD.table_count),json_object('table_count',NEW.table_count)); END;

CREATE TRIGGER history_completion_history_insert AFTER INSERT ON completion_history
BEGIN INSERT INTO action_history(kind,action,entity_type,entity_id,entity_name,tournament_id,tournament_name,category_id,category_name,before_data,after_data) VALUES('completion',CASE WHEN json_extract(NEW.payload,'$.completion.completed_at') IS NULL THEN 'reopened' ELSE 'completed' END,'completion_history',NEW.entity_id,COALESCE((SELECT name FROM categories WHERE id=NEW.entity_id),(SELECT name FROM tournaments WHERE id=NEW.entity_id)),CASE WHEN NEW.entity_kind='tournament' THEN NEW.entity_id ELSE (SELECT tournament_id FROM categories WHERE id=NEW.entity_id) END,(SELECT name FROM tournaments WHERE id=CASE WHEN NEW.entity_kind='tournament' THEN NEW.entity_id ELSE (SELECT tournament_id FROM categories WHERE id=NEW.entity_id) END),CASE WHEN NEW.entity_kind='category' THEN NEW.entity_id ELSE NULL END,(SELECT name FROM categories WHERE id=CASE WHEN NEW.entity_kind='category' THEN NEW.entity_id ELSE NULL END),(SELECT json_object('entity_kind',h.entity_kind,'revision',h.revision,'payload',h.payload) FROM completion_history h WHERE h.entity_kind=NEW.entity_kind AND h.entity_id=NEW.entity_id AND h.revision<NEW.revision ORDER BY h.revision DESC LIMIT 1),json_object('entity_kind',NEW.entity_kind,'revision',NEW.revision,'payload',NEW.payload)); END;

CREATE TRIGGER history_tournament_trash_insert AFTER INSERT ON tournament_trash
BEGIN INSERT INTO action_history(kind,action,entity_type,entity_id,entity_name,tournament_id,tournament_name,category_id,category_name,before_data,after_data) VALUES('trash','trashed','tournament_trash',NEW.tournament_id,(SELECT name FROM tournaments WHERE id=NEW.tournament_id),NEW.tournament_id,(SELECT name FROM tournaments WHERE id=NEW.tournament_id),NULL,(SELECT name FROM categories WHERE id=NULL),NULL,json_object()); END;

CREATE TRIGGER history_tournament_trash_delete AFTER DELETE ON tournament_trash
BEGIN INSERT INTO action_history(kind,action,entity_type,entity_id,entity_name,tournament_id,tournament_name,category_id,category_name,before_data,after_data) VALUES('trash','restored','tournament_trash',OLD.tournament_id,(SELECT name FROM tournaments WHERE id=OLD.tournament_id),OLD.tournament_id,(SELECT name FROM tournaments WHERE id=OLD.tournament_id),NULL,(SELECT name FROM categories WHERE id=NULL),json_object(),NULL); END;

PRAGMA user_version=20;
