<script lang="ts">
  import InfoRows from './InfoRows.svelte';
  import { onMount, untrack } from 'svelte';
  import CompletionControl from './CompletionControl.svelte';
  import PlayerName from './PlayerName.svelte';
  import Icon from './Icon.svelte';
  import { playerLabel } from './player-label';
  import { roundTitle } from './draw-view';
  import { getCategoryResults, desktopAvailable, type CategoryResults as Results, type Category, type Tournament, type FinalPlacement } from './api';
  import { messages, errorKey, type Language, type MessageKey } from './i18n';
  let {active=true,tournament,category,language,busy=$bindable(false),ontab}: {active?:boolean;tournament:Tournament;category:Category;language:Language;busy?:boolean;ontab:(tab:'matches'|'settings'|'groups')=>void}=$props();
  let sr=$derived(language==='sr');let text=$derived(messages[language]);let data=$state<Results|null>(null);let loading=$state(false);let writing=$state(false);let error=$state<MessageKey|null>(null);
  let names=$derived(new Map(data?.draw?.participants.map(e=>[e.id,e.members.map(playerLabel).join(' / ')])??[]));
  let podium=$derived([1,2,3].map(place=>({place,entries:data?.placements.filter(p=>p.place===place && p.stage!=='groups')??[]})).filter(item=>item.entries.length));
  $effect(()=>{busy=loading || writing;});
  async function load(){if(!desktopAvailable || writing || loading)return;loading=true;error=null;try{data=await getCategoryResults(tournament.id,category.id);}catch(cause){error=errorKey(cause);}finally{loading=false;}}
  onMount(()=>{void load();const refresh=(event:Event)=>{if((event as CustomEvent).detail===category.id && !writing)void load();};const completion=(event:Event)=>{if((event as CustomEvent).detail===tournament.id && !writing)void load();};window.addEventListener('librett-results-updated',refresh);window.addEventListener('librett-completion-updated',completion);return()=>{window.removeEventListener('librett-results-updated',refresh);window.removeEventListener('librett-completion-updated',completion);};});
  let wasActive=untrack(()=>active);$effect(()=>{if(active && !wasActive && !busy)void load();wasActive=active;});
  const blocker=(code:string)=>({no_draw:sr?'Nema sačuvanog žreba.':'No saved draw.',stale_draw:sr?'Žreb je zastareo ili nepotpun.':'The draw is outdated or incomplete.',group_matches:sr?'Nisu završeni svi grupni mečevi.':'Group matches are incomplete.',group_ranking:sr?'Razreši izjednačenje u plasmanu grupa.':'Resolve tied group standings.',qualification:sr?'Prolaznici / Lucky loser mesta čekaju izbor.':'Qualifiers / lucky loser places await selection.',knockout_matches:sr?'Nokaut mečevi i finale nisu završeni.':'Knockout matches and the final are incomplete.'}[code]??code);
  function stage(p:FinalPlacement){if(p.stage==='winner')return sr?'Pobednik':'Winner';if(p.stage==='finalist')return sr?'Finalista':'Finalist';if(p.stage==='groups')return sr?'Ispao u grupi':'Eliminated in groups';const size=2**(1+Math.max(0,...(data?.placements.map(item=>item.round??0)??[])));return roundTitle(size/2**(p.round??0),language);}
  function place(p:FinalPlacement){if(p.place===3 && p.stage==='knockout')return '3.';return p.place===p.place_end?`${p.place}.`:`${p.place}–${p.place_end}.`;}
  function changed(progress: import('./api').TournamentProgress){data=progress.categories.find(item=>item.category_id===category.id)??data;}
</script>
<section class="results-view">
  <div class="section-heading"><div><h2>{data?.completion.completed_at ? (sr?'Konačni plasman':'Final standings') : (sr?'Plasman kategorije':'Category standings')}</h2><p class="muted">{data?.completion.completed_at ? (sr?'Završena kategorija':'Completed category') : data?.ready ? (sr?'Rezultati su spremni za potvrdu završetka.':'Results are ready for completion confirmation.') : (sr?'Plasman se formira po završetku svih mečeva.':'Standings are formed once all matches finish.')}</p></div><button class="secondary icon-label" disabled={busy} onclick={load}><Icon name="restore" size={16} />{sr?'Osveži':'Refresh'}</button></div>
  {#if error}<p class="error" role="alert">{text[error]}</p>{/if}
  {#if loading}<p role="status">{text.loading}</p>{:else if !desktopAvailable}<p class="banner">{text.preview}</p>{:else if data}
    <div class="result-status"><span class="pill">{data.completion.completed_at ? (sr?'Završeno':'Completed') : data.ready ? (sr?'Spremno':'Ready') : (sr?'U toku':'In progress')}</span><InfoRows items={[{label:sr?'Grupe':'Groups',value:data.group_total?`${data.group_completed}/${data.group_total}`:null},{label:sr?'Nokaut':'Knockout',value:`${data.knockout_completed}/${data.knockout_total}`}]} />{#if data.completion.completed_at}<time datetime={data.completion.completed_at}>{new Date(data.completion.completed_at).toLocaleString(sr?'sr-Latn-RS':'en-GB')}</time>{/if}</div>
    {#if !data.ready}<ul class="blockers">{#each data.blockers as code}<li>{blocker(code)}</li>{/each}</ul><div class="form-actions"><button data-open-tab class="secondary" onclick={()=>ontab('matches')}>{text.matches}</button><button data-open-tab class="secondary" onclick={()=>ontab(category.format==='groups_knockout'?'groups':'settings')}>{category.format==='groups_knockout'?text.groups:text.settings}</button></div>
    {:else}
      <div class="podium">{#each podium as item (item.place)}<article class="podium-place" class:gold={item.place===1}><span class="medal"><Icon name="trophy" size={22} />{item.place}.</span><h3>{item.place===1?(sr?'Pobednik':'Winner'):item.place===2?(sr?'Finalista':'Finalist'):(sr?'Treće mesto':'Third place')}</h3>{#each item.entries as entry (entry.entry_id)}<p><PlayerName label={names.get(entry.entry_id)??entry.entry_id} /></p>{/each}</article>{/each}</div>
      <p class="muted placement-policy">{data.third_place==='bronze_match' ? sr?'Treće i četvrto mesto određuje meč za bronzu.':'Third and fourth places are decided by the bronze match.' : data.third_place==='champion_semifinalist' ? sr?'Treći je polufinalista koji je izgubio od kasnijeg pobednika turnira.':'Third is the semifinalist beaten by the eventual champion.' : sr?'Poraženi polufinalisti dele treće mesto.':'Losing semifinalists share third place.'} {sr?'Ostali dele raspon prema fazi ispadanja.':'Other entries share ranges by elimination stage.'}</p>
      <div class="results-scroll"><table><thead><tr><th>{sr?'Plasman':'Place'}</th><th>{sr?'Igrač / par':'Player / pair'}</th><th>{sr?'Faza':'Stage'}</th></tr></thead><tbody>{#each data.placements as placement (placement.entry_id)}<tr><td><b>{place(placement)}</b></td><td><PlayerName label={names.get(placement.entry_id)??placement.entry_id} /></td><td>{stage(placement)}</td></tr>{/each}</tbody></table></div>
    {/if}
    <div class="completion-actions"><CompletionControl tournamentId={tournament.id} categoryId={category.id} completion={data.completion} version={data.version} ready={data.ready} parentClosed={!!data.tournament_completion.completed_at} {language} bind:busy={writing} onchanged={changed} onreload={load} />{#if data.tournament_completion.completed_at}<span class="muted">{sr?'Za ispravke prvo otvori turnir u Pregledu.':'To make corrections, reopen the tournament in Overview first.'}</span>{/if}</div>
  {/if}
</section>
<style>
.results-view{min-width:0;}h2{margin:0;font-size:18px;}.section-heading{align-items:flex-start;flex-wrap:wrap;}.result-status{display:flex;gap:18px;align-items:center;flex-wrap:wrap;margin:20px 0;color:var(--text-secondary);font-size:12px;}time{color:var(--text-muted);}.blockers{padding-left:20px;color:var(--text-secondary);font-size:12px;line-height:2;}.podium{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:20px;margin:28px 0;}.podium-place{padding:24px;border:1px solid var(--border-subtle);border-radius:8px;background:var(--surface);}.gold{border-color:var(--primary);}.medal{display:flex;align-items:center;gap:10px;color:var(--text-secondary);font-size:20px;font-weight:600;}.gold .medal{color:var(--primary);}h3{font-size:11px;color:var(--text-muted);margin:14px 0 12px;} .podium-place p{font-size:14px;line-height:1.6;margin:6px 0;overflow-wrap:anywhere;}.placement-policy{line-height:1.7;}.results-scroll{overflow:auto;margin-top:20px;}table{width:100%;border-collapse:collapse;font-size:12px;}th,td{text-align:left;padding:14px 12px;border-bottom:1px solid var(--border-subtle);}th{font-size:11px;color:var(--text-secondary);}td:first-child{width:90px;}td:last-child{color:var(--text-muted);}.completion-actions{display:flex;align-items:center;gap:16px;flex-wrap:wrap;margin-top:28px;}@media(max-width:800px){.podium{grid-template-columns:1fr;}}
</style>
