import type {Language} from './i18n';
export interface GuideStep {title:string;steps:string[];note?:string}
export interface Guide {title:string;intro:string;steps:GuideStep[];help:{title:string;answer:string}[];terms:{word:string;meaning:string}[]}
export const tournamentGuides:Record<Language,Guide>={
  sr:{
    title:'Kako vodiš turnir',intro:'Prati korake redom. Ako je nešto već urađeno, pređi na sledeći korak. Ovaj vodič možeš ponovo otvoriti u levom meniju.',
    steps:[
      {title:'Napravi turnir',steps:['U levom meniju otvori Turniri, pa klikni Dodaj turnir.','Upiši naziv, na primer „Bubušinac 2027”. Naslovna slika nije obavezna.','Sačuvaj i otvori karticu tog turnira.']},
      {title:'Dodaj igrače',steps:['U levom meniju otvori Igrači, pa dodaj igrača.','Upiši ime, godište i klub. Godište je obavezno. Slika i kontakt nisu obavezni.','Za klub biraj postojeći naziv kada ga ima. Ako se pojavi predlog za sličan naziv, proveri ga i klikni da ga prihvatiš.'],note:'Klub ispravi pre prijave u kategoriju: izmena profila ne menja naziv kluba u već sačuvanoj prijavi.'},
      {title:'Napravi kategorije',steps:['Vrati se u turnir i otvori Kategorije → Dodaj kategoriju.','Upiši naziv, na primer „Singl 40+”. Izaberi singl ili dubl.','Izaberi direktni nokaut ili grupe pa nokaut. Za grupe unesi broj grupa i koliko učesnika prolazi iz svake.','Odredi broj setova, poene za set i potrebnu razliku. Po potrebi uključi starosni raspon.','Izaberi BYE ili lucky loser i kako se određuje treće mesto. U grupama izaberi da li isti klub sme u jednu automatsku grupu. Sačuvaj.'],note:'Starosna granica daje upozorenje; organizator može da potvrdi izuzetak. Ako nisi siguran u pravila, prvo ih usaglasi sa organizatorima turnira.'},
      {title:'Prijavi učesnike',steps:['Otvori kategoriju, pa Prijave.','Izaberi igrače i sačuvaj prijave. Za dubl sastavi par od dva različita igrača.','Ponovi za sve kategorije. Isti igrač može biti prijavljen u više kategorija.','Proveri imena, klubove i broj prijavljenih pre pravljenja žreba.']},
      {title:'Potvrdi dolaske',steps:['Kada igrač stigne, u Prijavama označi da je došao.','Oznaka dolaska važi za tog igrača u celom turniru. U dublu potvrdi oba člana.','Ako igrač odustane pre početka kategorije, povuci njegovu prijavu.'],note:'Pre prvog rezultata aplikacija traži potvrđene dolaske. Možeš izričito potvrditi početak bez svih dolazaka, ali to samo po sebi ne omogućava naplatu.'},
      {title:'Evidentiraj kotizacije',steps:['U turniru otvori Blagajna.','Za prisutnog igrača izaberi kategorije koje plaća i evidentiraj uplatu.','Proveri dugovanje i sačuvane uplate. Za igrače koji nisu stigli prikazuje se očekivani iznos.','Ako vraćaš novac, koristi povraćaj u Blagajni.'],note:'Blagajna ostaje dostupna i posle završetka turnira.'},
      {title:'Napravi i proveri žreb',steps:['U kategoriji otvori Podešavanja i pronađi Nosioci i raspored.','Ako ima nosilaca, dodaj ih od najjačeg ka slabijem.','Izaberi automatski ili ručni raspored, napravi ga i proveri sva mesta. Zatim sačuvaj nacrt.','Otvori Grupe za pregled grupa i Žreb za nokaut kostur. Direktni nokaut nema grupnu fazu.','U Žreb → Uredi možeš promeniti mesta učesnika. U grupnom nokautu to radiš kada su sve grupe završene i plasman razrešen.'],note:'Ako je razdvajanje klubova uključeno, a automatski raspored nije pronađen, proveri nazive klubova, nosioce i broj grupa ili izaberi ručni raspored.'},
      {title:'Sačuvaj rezervnu kopiju',steps:['U levom meniju otvori Rezervne kopije.','Klikni Napravi kopiju pre početka mečeva.','Ako želiš kopiju i na drugom mestu, izvezi je pa kopiraj taj fajl, na primer na USB.'],note:'Rezervna kopija sadrži ceo turnir i ostale podatke aplikacije.'},
      {title:'Unosi rezultate mečeva',steps:['Otvori kategoriju → Mečevi i izaberi grupu i kolo ili nokaut fazu.','Na odgovarajućem meču klikni Uredi. Ako dodeljuješ sto, unesi broj i prvo sačuvaj sto.','Unesi poene svakog seta, na primer 11:7, 11:9 i 11:5. Broj potrebnih pobeda zavisi od izabranog broja setova.','Za normalan meč izaberi Odigran meč. Za odustajanje tokom meča izaberi Predaja, a za nedolazak Nedolazak, pa izaberi pobednika.','Sačuvaj rezultat. Proveri da je označen pravi pobednik.'],note:'Novi rezultat ažurira tabele grupa i naredne nokaut mečeve. Ne unosi dodatne setove nakon što je meč odlučen.'},
      {title:'Završi grupe i proveri prolaznike',steps:['Ako se igraju grupe, unesi sve grupne mečeve i otvori Grupe.','Ako plasman ostane izjednačen, proveri rezultate i po potrebi potvrdi ručni plasman.','U Žrebu proveri prolaznike i lucky loser mesta. Automatski izbor čeka da sve grupe budu završene.','Za ručni izbor otvori Žreb → Uredi i izaberi učesnika ili BYE. Kada automatski kandidati ostanu izjednačeni na poslednjem mestu, razreši izbor ručno.'],note:'BYE znači slobodan prolaz. Lucky loser je učesnik ispod granice prolaska koji dobija dodatno mesto. Ako nema dovoljno kandidata za automatsku popunu, preostala mesta postaju BYE.'},
      {title:'Završi kategoriju',steps:['Unesi nokaut rezultate do finala. Ako je izabran meč za treće mesto, unesi i njega.','Otvori Rezultati i proveri konačni plasman. Ako nešto nedostaje, aplikacija pokazuje šta treba dovršiti.','Klikni Završi kategoriju i potvrdi. Uradi to za svaku kategoriju.'],note:'Završena kategorija zaključava prijave, pravila, žreb i rezultate. Za ispravku je prvo ponovo otvori u Rezultatima.'},
      {title:'Završi turnir i sačuvaj rezultate',steps:['U turniru otvori Pregled i proveri da su sve aktivne kategorije završene.','Klikni Završi turnir i potvrdi.','Tamo gde su ponuđeni izveštaji, koristi Štampa / PDF, CSV ili HTML da sačuvaš ili odštampaš rezultate.','Napravi još jednu rezervnu kopiju i izvezi je na sigurno mesto.'],note:'Ako treba ispravka nakon završetka turnira, prvo ponovo otvori turnir u Pregledu, zatim kategoriju u Rezultatima. Posle ispravke ponovo potvrdi oba završetka.'},
    ],
    help:[
      {title:'Pogrešno sam uneo rezultat.',answer:'Otvori isti meč, klikni Uredi i sačuvaj ispravku. Ako se menjaju učesnici narednih mečeva, aplikacija traži potvrdu poništavanja njihovih rezultata. Posle potvrde proveri te mečeve i unesi važeće rezultate.'},
      {title:'Igrač je odustao kada je kategorija već počela.',answer:'Prijava ostaje sačuvana. U odgovarajućim mečevima evidentiraj Predaja ili Nedolazak i izaberi pobednika. Započeta kategorija ne može da se ukloni.'},
      {title:'Hoću novi žreb ili drugačije bodovanje posle početka.',answer:'Novi žreb traži potvrdu i počinje bez prethodnih rezultata i dodeljenih stolova. Stari zapisi ostaju u istoriji. Promena bodovanja takođe traži potvrdu: stari rezultati zadržavaju svoja pravila, a naredni unosi i ispravke koriste nova.'},
      {title:'Gde vidim šta je menjano?',answer:'Otvori Istorija u levom meniju. Najnovija akcija je prva. Izaberi turnir, vrstu istorije ili akciju, pa otvori detalje zapisa.'},
      {title:'Kako vraćam podatke iz kopije?',answer:'U Rezervnim kopijama izaberi Vrati podatke ili Vrati kopiju iz fajla. To zamenjuje celu bazu, ne samo jedan turnir. Aplikacija prvo čuva trenutno stanje, a zatim se ponovo učitava i zatvara otvorene tabove.'},
    ],
    terms:[{word:'Kategorija',meaning:'Posebno takmičenje u turniru, na primer singl 40+ ili dubl.'},{word:'Nosilac',meaning:'Učesnik čiji rang organizator koristi pri raspoređivanju.'},{word:'Nokaut',meaning:'Pobednik nastavlja; poraženi ispada iz borbe za prvo mesto.'},{word:'Set',meaning:'Jedan deo meča. Meč se dobija potrebnim brojem osvojenih setova.'}],
  },
  en:{
    title:'How to run a tournament',intro:'Follow the steps in order. Skip anything you have already done. You can reopen this guide from the left menu at any time.',
    steps:[
      {title:'Create a tournament',steps:['Open Tournaments in the left menu and choose Add tournament.','Enter a name, such as “Bubušinac 2027”. A cover image is optional.','Save, then open the tournament card.']},
      {title:'Add players',steps:['Open Players in the left menu and add a player.','Enter their name, birth year and club. Birth year is required; photos and contact details are optional.','Choose an existing club name when available. Check any similar-name suggestion and click it to accept it.'],note:'Correct clubs before registration: editing a profile does not change the club saved in an existing registration.'},
      {title:'Create categories',steps:['Open the tournament, then Categories → Add category.','Enter a name such as “Singles 40+”. Choose singles or doubles.','Choose direct knockout or groups followed by knockout. For groups, set the number of groups and qualifiers per group.','Set the number of sets, points to win a set and winning margin. Enable an age range if needed.','Choose BYE or lucky losers, the third-place rule, and whether clubmates may share an automatic group. Save.'],note:'Age limits show a warning; organizers may confirm exceptions. Agree the rules with your tournament organizers before starting.'},
      {title:'Register participants',steps:['Open a category, then Registrations.','Choose players and save their registrations. For doubles, build a pair of two different players.','Repeat for every category. A player may enter several categories.','Check names, clubs and participant counts before creating the draw.']},
      {title:'Confirm arrivals',steps:['When a player arrives, mark them as arrived in Registrations.','Arrival applies across that tournament. Confirm both doubles members.','Withdraw registrations for players who drop out before the category starts.'],note:'Before the first result, the app checks arrivals. An explicit organizer override allows starting without every arrival; it does not enable collecting payment from unconfirmed arrivals.'},
      {title:'Record entry fees',steps:['Open the tournament Cash desk.','For an arrived player, select the categories they are paying for and record payment.','Check outstanding balances and payments. Unconfirmed arrivals show an expected amount.','Use the refund action if you return money.'],note:'The cash desk remains available after tournament completion.'},
      {title:'Create and check the draw',steps:['Open category Settings and find Seeds and arrangement.','Add seeds in order, strongest first, if applicable.','Choose automatic or manual arrangement, generate it, check every place, then save the draft.','Open Groups for group standings and Draw for the knockout bracket. Direct knockout has no group phase.','Use Draw → Edit to change opening-round places. Group knockout editing is available after all groups finish and standings are resolved.'],note:'If club separation cannot find a layout, check club names, seeds and group count, or choose a manual layout.'},
      {title:'Make a backup',steps:['Open Backups in the left menu.','Choose Create backup before matches begin.','Export a copy and copy the exported file elsewhere, such as a USB drive, if needed.'],note:'A backup includes this tournament and the rest of the application database.'},
      {title:'Enter match results',steps:['Open category Matches and choose the group and round or knockout stage.','Choose Edit on the correct match. If assigning a table, enter its number and save the table first.','Enter each set’s points, such as 11:7, 11:9 and 11:5. Required set wins depend on the category rules.','Use Played match for a normal ending. Choose Retired for withdrawal during a match or Walkover for a no-show, then choose the winner.','Save the result and check that the correct winner is shown.'],note:'Saved results update group standings and subsequent knockout matches. Do not enter extra sets once the match has been decided.'},
      {title:'Finish groups and check qualifiers',steps:['If using groups, enter every group match and open Groups.','If standings remain tied, check results and confirm a manual ranking if needed.','Check qualifiers and lucky-loser places in Draw. Automatic selection waits for every group to finish.','For manual selection, use Draw → Edit to choose an entrant or BYE. Resolve any tied automatic candidates at the final available place manually.'],note:'BYE means automatic advance. A lucky loser is an entrant below the qualification cutoff who receives an extra place. Automatic filling uses BYE for remaining places if there are not enough candidates.'},
      {title:'Complete each category',steps:['Enter knockout results through the final, including a bronze match if the rules require one.','Open Results and check final standings. The app lists anything still needed.','Choose Complete category and confirm. Repeat for all categories.'],note:'Completion locks registrations, rules, draws and results. Reopen a category in Results before making corrections.'},
      {title:'Complete the tournament and save reports',steps:['Open tournament Overview and check that every active category is complete.','Choose Complete tournament and confirm.','Where report controls are available, use Print / PDF, CSV or HTML to save or print reports.','Create another backup and export it to a safe location.'],note:'For corrections after tournament completion, reopen the tournament in Overview, then the category in Results. Confirm both completions again afterwards.'},
    ],
    help:[
      {title:'I entered the wrong result.',answer:'Edit the same match and save the correction. If subsequent participants change, the app asks before clearing dependent results. Check those matches and enter valid results after confirmation.'},
      {title:'A player withdrew after the category started.',answer:'Keep the registration. Record Retired or Walkover in the affected matches and choose the winner. Started categories cannot be removed.'},
      {title:'I want a new draw or scoring rules after play starts.',answer:'A new draw requires confirmation and starts without previous scores or table assignments. Old records stay in history. Scoring changes also require confirmation: old results keep their original rules; subsequent entries and corrections use the new rules.'},
      {title:'Where can I see changes?',answer:'Open History in the left menu. Newest actions appear first. Filter by tournament, history type or action, then expand record details.'},
      {title:'How do I restore a backup?',answer:'Open Backups and choose Restore data or Restore from file. This replaces the whole database, not just one tournament. The app saves the current database first, then reloads and closes open tabs.'},
    ],
    terms:[{word:'Category',meaning:'A separate competition within a tournament, such as singles 40+ or doubles.'},{word:'Seed',meaning:'A participant ranked by the organizer for draw placement.'},{word:'Knockout',meaning:'Winners advance; losers leave the contest for first place.'},{word:'Set',meaning:'One part of a match. A match is won by winning the required number of sets.'}],
  },
};
