import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import ts from 'typescript';

const source = await readFile(new URL('../apps/desktop/src/cash-balance.ts', import.meta.url), 'utf8');
const code = ts.transpileModule(source, {compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
const {cashBalance} = await import('data:text/javascript;base64,' + Buffer.from(code).toString('base64'));
const category = {id:'category',archived:false};
const entry = {id:'entry',status:'registered',members:[{id:'a',checked_in:false},{id:'b',checked_in:false}]};
const ledger = {records:[{id:'fee',entry_id:'entry',kind:'charge',amount_minor:501}],allocations:[]};
const balance = (id) => cashBalance(entry,category,ledger,id);
assert.equal(balance('a').remaining,0);
assert.equal(balance('a').expected,251);
assert.equal(balance('b').expected,250);
entry.members[0].checked_in = true;
assert.equal(balance('a').remaining,251);
assert.equal(balance('a').expected,0);
assert.equal(balance('b').remaining,0);
ledger.records.push({id:'paid',entry_id:'entry',kind:'payment',amount_minor:251});
ledger.allocations.push({record_id:'paid',player_id:'a',amount_minor:251});
assert.equal(balance('a').remaining,0);
assert.equal(balance('a').net,251);
assert.equal(balance('b').expected,250);
entry.status = 'withdrawn';
assert.equal(balance('b').expected,0);
assert.equal(balance('b').remaining,0);
assert.equal(balance('a').eligible,false);
assert.equal(balance('a').net,251); // Refund remains available without creating debt.
ledger.records.push({id:'refund',entry_id:'entry',kind:'refund',amount_minor:251});
ledger.allocations.push({record_id:'refund',player_id:'a',amount_minor:251});
assert.equal(balance('a').remaining,0);
assert.equal(balance('a').net,0);
entry.status = 'registered';
assert.equal(balance('a').remaining,251);
assert.equal(balance('b').expected,250);
category.archived = true;
assert.equal(balance('a').remaining,0);
assert.equal(balance('b').expected,0);
category.archived = false;
// Historical unallocated doubles payments retain the same integer split.
ledger.records = [{id:'fee',entry_id:'entry',kind:'charge',amount_minor:501},{id:'historical',entry_id:'entry',kind:'payment',amount_minor:101}];
ledger.allocations = [];
assert.equal(balance('a').net,51);
assert.equal(balance('b').net,50);
assert.equal(balance('a').remaining,200);
assert.equal(balance('b').expected,200);
entry.members[0].checked_in = false;
assert.equal(balance('a').remaining,0);
assert.equal(balance('a').expected,200);
console.log('Cash calculations: arrival estimates, active debt, withdrawals, refunds, restoration and doubles rounding passed.');
